Loading the data processed by hdWGCNA in R

In [1]:
import math
import seaborn as sns
import numpy as np
import scanpy as sc
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from abc_atlas_access.abc_atlas_cache.abc_project_cache import AbcProjectCache

In [2]:
# Selecting the brain region
select_region = "Isocortex-1"

In [3]:
# Loading AnnData object
base_path = Path("/data/scRNA/ABCA/AIBS/AWS/expression_matrices/WMB-10Xv3/20230630/")
expr_path = base_path / f"WMB-10Xv3-{select_region}-raw-wmeta.h5ad"
adata = sc.read_h5ad(expr_path)
adata

AnnData object with n_obs × n_vars = 227670 × 32285
    obs: 'cell_barcode', 'barcoded_cell_sample_label', 'library_label', 'feature_matrix_label', 'entity', 'brain_section_label', 'library_method', 'region_of_interest_acronym', 'donor_label', 'donor_genotype', 'donor_sex', 'dataset_label', 'x', 'y', 'cluster_alias', 'neurotransmitter', 'class', 'subclass', 'supertype', 'cluster', 'neurotransmitter_color', 'class_color', 'subclass_color', 'supertype_color', 'cluster_color', 'region_of_interest_order', 'region_of_interest_color'
    var: 'gene_symbol'

In [4]:
# Loading Module Eigengenes dataframe
base_path = Path("/data/scRNA/ABCA/AIBS/AWS/expression_matrices/WMB-10Xv3/20230630/outputs")
modules_df = pd.read_csv(base_path / f"WMB-10Xv3-{select_region}-raw-mc-wgcna-modules.csv", index_col="Unnamed: 0")
modules_df.head()

,gene_name,module,color,kME_Isocortex-M1,kME_Isocortex-M2,kME_Isocortex-M3,kME_Isocortex-M4,kME_grey,kME_Isocortex-M5,kME_Isocortex-M6,kME_Isocortex-M7,kME_Isocortex-M8,kME_Isocortex-M9
ENSMUSG00000015090,ENSMUSG00000015090,Isocortex-M1,yellow,0.645442,-0.082131,0.055263,0.123491,-0.087391,0.096088,0.129945,0.244009,0.606363,-0.205105
ENSMUSG00000031425,ENSMUSG00000031425,Isocortex-M1,yellow,0.919267,-0.107151,0.070567,0.095239,-0.112462,0.107643,0.243849,0.051845,0.041710,-0.244151
ENSMUSG00000115529,ENSMUSG00000115529,Isocortex-M1,yellow,0.290416,-0.025055,0.009020,0.027299,-0.029463,0.038628,0.236592,0.012456,0.003026,-0.099603
ENSMUSG00000029819,ENSMUSG00000029819,Isocortex-M2,turquoise,-0.003594,0.542115,0.002021,-0.003075,-0.085746,-0.004960,0.046668,0.012330,0.004241,-0.161405
ENSMUSG00000024610,ENSMUSG00000024610,Isocortex-M3,blue,0.006335,-0.033054,0.153545,0.040280,-0.027896,0.001917,-0.002614,0.018507,0.042056,-0.035275

In [6]:
# Loading Module Eigengenes dataframe
base_path = Path("/data/scRNA/ABCA/AIBS/AWS/expression_matrices/WMB-10Xv3/20230630/outputs")
MEs_df = pd.read_csv(base_path / f"WMB-10Xv3-{select_region}-raw-mc-wgcna-MEs.csv", index_col="Unnamed: 0")
MEs_df = MEs_df.drop(columns=["grey"])
MEs_df.head()

,red,turquoise,blue,brown,magenta,pink,yellow,green,black
GCACTAAGTACAAGTA-399_B02,2.988262,-0.787622,-1.016958,-1.215624,-0.174549,0.647710,-1.217256,-0.831952,-0.595370
CAGAGCCGTCCTGGTG-399_A02,2.427436,-1.750801,-1.532274,-1.917022,-0.187433,-0.396619,-1.841867,-2.073541,-1.146416
CGCCATTCACGACAGA-403_A06,1.901891,0.278857,-1.078494,-1.361532,-0.740149,-0.427430,-2.059687,-2.341675,-1.175005
GGGTTTATCCGATCGG-399_B02,1.741183,-0.799985,-1.095999,-1.159304,-0.194344,0.064914,-1.383718,-2.137136,-1.376131
GTGTGATCAGACAAAT-399_B02,3.110689,-2.819272,-0.584560,-1.144549,-0.236718,-0.611864,-1.330379,-2.046524,-1.141430

In [7]:
# Create a mapping from color to module
color_to_module = modules_df.set_index("color")["module"].to_dict()

# Rename the columns of MEs_df
MEs_df.rename(columns=color_to_module, inplace=True)

# Sort the columns of MEs_df alphabetically
MEs_df = MEs_df.reindex(sorted(MEs_df.columns), axis=1)
MEs_df.head()

,Isocortex-M1,Isocortex-M2,Isocortex-M3,Isocortex-M4,Isocortex-M5,Isocortex-M6,Isocortex-M7,Isocortex-M8,Isocortex-M9
GCACTAAGTACAAGTA-399_B02,-1.217256,-0.787622,-1.016958,-1.215624,-0.831952,-0.595370,-0.174549,0.647710,2.988262
CAGAGCCGTCCTGGTG-399_A02,-1.841867,-1.750801,-1.532274,-1.917022,-2.073541,-1.146416,-0.187433,-0.396619,2.427436
CGCCATTCACGACAGA-403_A06,-2.059687,0.278857,-1.078494,-1.361532,-2.341675,-1.175005,-0.740149,-0.427430,1.901891
GGGTTTATCCGATCGG-399_B02,-1.383718,-0.799985,-1.095999,-1.159304,-2.137136,-1.376131,-0.194344,0.064914,1.741183
GTGTGATCAGACAAAT-399_B02,-1.330379,-2.819272,-0.584560,-1.144549,-2.046524,-1.141430,-0.236718,-0.611864,3.110689

In [8]:
# Getting the list of modules
modules = MEs_df.columns.tolist()

In [9]:
# Adding MEs to AnnData object
merged_df = pd.merge(adata.obs, MEs_df, left_index=True, right_index=True)
merged_df.head()

,cell_barcode,barcoded_cell_sample_label,library_label,feature_matrix_label,entity,brain_section_label,library_method,region_of_interest_acronym,donor_label,donor_genotype,...,region_of_interest_color,Isocortex-M1,Isocortex-M2,Isocortex-M3,Isocortex-M4,Isocortex-M5,Isocortex-M6,Isocortex-M7,Isocortex-M8,Isocortex-M9
GCACTAAGTACAAGTA-399_B02,GCACTAAGTACAAGTA,399_B02,L8TX_201022_01_H06,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,RSP,Snap25-IRES2-Cre;Ai14-546810,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,...,#E4FF26,-1.217256,-0.787622,-1.016958,-1.215624,-0.831952,-0.595370,-0.174549,0.647710,2.988262
CAGAGCCGTCCTGGTG-399_A02,CAGAGCCGTCCTGGTG,399_A02,L8TX_201023_01_A09,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,RSP,Snap25-IRES2-Cre;Ai14-546810,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,...,#E4FF26,-1.841867,-1.750801,-1.532274,-1.917022,-2.073541,-1.146416,-0.187433,-0.396619,2.427436
CGCCATTCACGACAGA-403_A06,CGCCATTCACGACAGA,403_A06,L8TX_201022_01_B07,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,RSP,Snap25-IRES2-Cre;Ai14-547057,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,...,#E4FF26,-2.059687,0.278857,-1.078494,-1.361532,-2.341675,-1.175005,-0.740149,-0.427430,1.901891
GGGTTTATCCGATCGG-399_B02,GGGTTTATCCGATCGG,399_B02,L8TX_201022_01_H06,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,RSP,Snap25-IRES2-Cre;Ai14-546810,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,...,#E4FF26,-1.383718,-0.799985,-1.095999,-1.159304,-2.137136,-1.376131,-0.194344,0.064914,1.741183
GTGTGATCAGACAAAT-399_B02,GTGTGATCAGACAAAT,399_B02,L8TX_201022_01_H06,WMB-10Xv3-Isocortex-1,cell,NaN,10Xv3,RSP,Snap25-IRES2-Cre;Ai14-546810,Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt,...,#E4FF26,-1.330379,-2.819272,-0.584560,-1.144549,-2.046524,-1.141430,-0.236718,-0.611864,3.110689

## Gene Ontology

In [ ]:
# For one module
from gprofiler import GProfiler

# Initialize GProfiler
gp = GProfiler(return_dataframe=True)

# Select genes from a specific module
module_name = "Isocortex-M1"
genes_of_module = modules_df[modules_df["module"] == module_name]["gene_name"].tolist()

# Perform GO enrichment analysis
go_results = gp.profile(organism='mmusculus', query=genes_of_module)

# Display the results
go_results.head()

,source,native,name,p_value,significant,description,term_size,query_size,intersection_size,effective_domain_size,precision,recall,query,parents
0,GO:BP,GO:0008366,axon ensheathment,1.248789e-25,True,"""Any process in which the axon of a neuron is ...",190,169,27,26963,0.159763,0.142105,query_1,[GO:0007272]
1,GO:BP,GO:0007272,ensheathment of neurons,1.248789e-25,True,"""The process in which glial cells envelop neur...",190,169,27,26963,0.159763,0.142105,query_1,"[GO:0007399, GO:0009987]"
2,GO:BP,GO:0022008,neurogenesis,1.551041e-24,True,"""Generation of cells within the nervous system...",1907,169,61,26963,0.360947,0.031987,query_1,"[GO:0007399, GO:0030154]"
3,GO:BP,GO:0007399,nervous system development,1.945909e-24,True,"""The process whose specific outcome is the pro...",2531,169,69,26963,0.408284,0.027262,query_1,[GO:0048731]
4,GO:BP,GO:0042552,myelination,2.498312e-24,True,"""The process in which myelin sheaths are forme...",187,169,26,26963,0.153846,0.139037,query_1,[GO:0008366]

In [12]:
go_results

,source,native,name,p_value,significant,description,term_size,query_size,intersection_size,effective_domain_size,precision,recall,query,parents
0,GO:BP,GO:0008366,axon ensheathment,1.248789e-25,True,"""Any process in which the axon of a neuron is ...",190,169,27,26963,0.159763,0.142105,query_1,[GO:0007272]
1,GO:BP,GO:0007272,ensheathment of neurons,1.248789e-25,True,"""The process in which glial cells envelop neur...",190,169,27,26963,0.159763,0.142105,query_1,"[GO:0007399, GO:0009987]"
2,GO:BP,GO:0022008,neurogenesis,1.551041e-24,True,"""Generation of cells within the nervous system...",1907,169,61,26963,0.360947,0.031987,query_1,"[GO:0007399, GO:0030154]"
3,GO:BP,GO:0007399,nervous system development,1.945909e-24,True,"""The process whose specific outcome is the pro...",2531,169,69,26963,0.408284,0.027262,query_1,[GO:0048731]
4,GO:BP,GO:0042552,myelination,2.498312e-24,True,"""The process in which myelin sheaths are forme...",187,169,26,26963,0.153846,0.139037,query_1,[GO:0008366]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166,WP,WP:WP2910,Mecp2 and associated Rett syndrome,4.239981e-02,True,Mecp2 and associated Rett syndrome,47,44,4,4532,0.090909,0.085106,query_1,[WP:000000]
167,TF,TF:M03814,Factor: BTEB2; motif: GNAGGGGGNGGGSSNN,4.332245e-02,True,Factor: BTEB2; motif: GNAGGGGGNGGGSSNN,4958,162,60,21628,0.370370,0.012102,query_1,[TF:M00000]
168,GO:BP,GO:0048519,negative regulation of biological process,4.413018e-02,True,"""Any process that stops, prevents, or reduces ...",5981,169,61,26963,0.360947,0.010199,query_1,"[GO:0008150, GO:0050789]"
169,GO:BP,GO:0030336,negative regulation of cell migration,4.424605e-02,True,"""Any process that stops, prevents, or reduces ...",307,169,10,26963,0.059172,0.032573,query_1,"[GO:0016477, GO:0030334, GO:2000146]"
170,GO:BP,GO:0051240,positive regulation of multicellular organisma...,4.484004e-02,True,"""Any process that activates or increases the f...",1822,169,27,26963,0.159763,0.014819,query_1,"[GO:0032501, GO:0048518, GO:0051239]"

In [ ]:
# For all modules
from gprofiler import GProfiler

for module_name in modules:
    # Initialize GProfiler
    gp = GProfiler(return_dataframe=True)
    
    # Select genes from a specific module
    genes_of_module = modules_df[modules_df["module"] == module_name]["gene_name"].tolist()

    # Perform GO enrichment analysis
    go_results = gp.profile(organism='mmusculus', query=genes_of_module)

    # Display the results
    go_results.to_csv(f"/data/scRNA/ABCA/AIBS/AWS/expression_matrices/WMB-10Xv3/20230630/outputs/GO/{module_name}_GO.csv")
    print(f"Module saved: {module_name}")