In [1]:
import math
import seaborn as sns
import numpy as np
import scanpy as sc
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from abc_atlas_access.abc_atlas_cache.abc_project_cache import AbcProjectCache

In [14]:
# Selecting the brain region
select_region = "Microglia"

In [15]:
# Loading AnnData object
base_path = Path("/data/scRNA/ABCA/AIBS/AWS/expression_matrices/WMB-10Xv3/20230630/")
expr_path = base_path / f"WMB-10Xv3-{select_region}-raw-wmeta.h5ad"
adata = sc.read_h5ad(expr_path)
adata

AnnData object with n_obs × n_vars = 81472 × 32285
    obs: 'cell_barcode', 'barcoded_cell_sample_label', 'library_label', 'feature_matrix_label', 'entity', 'brain_section_label', 'library_method', 'region_of_interest_acronym', 'donor_label', 'donor_genotype', 'donor_sex', 'dataset_label', 'x', 'y', 'cluster_alias', 'neurotransmitter', 'class', 'subclass', 'supertype', 'cluster', 'neurotransmitter_color', 'class_color', 'subclass_color', 'supertype_color', 'cluster_color', 'region_of_interest_order', 'region_of_interest_color', 'batch'
    var: 'gene_symbol'

In [16]:
# Loading Module Eigengenes dataframe
base_path = Path("/data/scRNA/ABCA/AIBS/AWS/expression_matrices/WMB-10Xv3/20230630/outputs")
hubs_df = pd.read_csv(base_path / f"WMB-10Xv3-{select_region}-raw-mc-wgcna-hubs.csv", index_col="Unnamed: 0")
hubs_df.head()

            gene_name module       kME
1  ENSMUSG00000038418  MG-M1  0.772310
2  ENSMUSG00000021025  MG-M1  0.747866
3  ENSMUSG00000035356  MG-M1  0.732437
4  ENSMUSG00000053560  MG-M1  0.731475
5  ENSMUSG00000021250  MG-M1  0.667237

In [17]:
# Map gene names to gene symbols using adata.var["gene_symbol"]
gene_symbol_mapping = adata.var["gene_symbol"].to_dict()

# Add a new column 'gene_symbol' to hubs_df
hubs_df["gene_symbol"] = hubs_df["gene_name"].map(gene_symbol_mapping)

# Display the updated dataframe
hubs_df.head()

            gene_name module       kME gene_symbol
1  ENSMUSG00000038418  MG-M1  0.772310        Egr1
2  ENSMUSG00000021025  MG-M1  0.747866      Nfkbia
3  ENSMUSG00000035356  MG-M1  0.732437      Nfkbiz
4  ENSMUSG00000053560  MG-M1  0.731475        Ier2
5  ENSMUSG00000021250  MG-M1  0.667237         Fos

In [18]:
# Loading Module Eigengenes dataframe
base_path = Path("/data/scRNA/ABCA/AIBS/AWS/expression_matrices/WMB-10Xv3/20230630/outputs")
hubs_df.to_csv(base_path / f"WMB-10Xv3-{select_region}-raw-mc-wgcna-hubs-mod.csv")

In [19]:
del adata, hubs_df